### Sign-up

POST http://localhost:8080/public/v1/auth/sign-up
Content-Type: application/json

{
  "name": "German",
  "surname": "Bogatov",
  "email": "bogatov@mail.ru",
  "password": "23Bogatov"
}

### Sign-in

POST http://localhost:8080/public/v1/auth/sign-in
Content-Type: application/json

{
  "email": "bogatov@mail.ru",
  "password": "23Bogatov"
}

### Refresh
POST http://localhost:8000/auth/refresh=dd7e03e1-8000-40c6-a722-e1bd064e2b65
Content-Type: application/json


### Get User By ID
POST http://localhost:8080/public/v1/users/5993e495-c7db-4060-853b-c98315ea8c95
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ1c2VycyIsImV4cCI6MTcyNzUzMzExOCwianRpIjoiYThmODdhNDctM2JlNy00M2Q0LThlNzMtYjJkZWNiNTMzYzM3IiwiZW1haWwiOiJib2dhdG92QG1haWwucnUifQ.p3s2b-Zdzovi0cjTWkIllSzrwfw6PWO4__tCMWnQyYU

